const express = require('express');
const cors = require('cors');
const tasksRouter = require('./routes/tasks');
const subtasksRouter = require('./routes/subtasks');
const app = express();
app.use(cors());
app.use(express.json());
app.use('/tasks', tasksRouter);
app.use('/tasks/:taskId/subtasks', subtasksRouter);
app.use('/subtasks', subtasksRouter);
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));